#!/usr/bin/env bash

set -Eeuo pipefail

PROJECT_NAME="spring-api-enterprise"
ROOT="$HOME/java-projects"
PROJECT_DIR="$ROOT/$PROJECT_NAME"

echo "========================================"
echo " DotNetProjectWizard"
echo " Spring API Enterprise Generator"
echo "========================================"
echo

# Verificar dependências
for cmd in curl unzip git; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "ERROR: '$cmd' não está instalado."
        exit 1
    fi
done

mkdir -p "$ROOT"
cd "$ROOT"

# Remover projeto antigo
rm -rf "$PROJECT_DIR"
rm -f "${PROJECT_NAME}.zip"

echo "[1/7] Baixando projeto do Spring Initializr..."

curl -fsSL \
"https://start.spring.io/starter.zip?type=maven-project&language=java&baseDir=${PROJECT_NAME}&groupId=com.example&artifactId=${PROJECT_NAME}&name=${PROJECT_NAME}&packageName=com.example.api&javaVersion=17&dependencies=web,data-jpa,security,validation,postgresql" \
-o "${PROJECT_NAME}.zip"

echo "[2/7] Extraindo projeto..."

unzip -q "${PROJECT_NAME}.zip"

rm "${PROJECT_NAME}.zip"

if [ ! -d "$PROJECT_DIR" ]; then
    echo
    echo "ERRO: o Spring Initializr não gerou o projeto."
    exit 1
fi

echo "[3/7] Criando docker-compose.yml..."

cat > "$PROJECT_DIR/docker-compose.yml" <<'DOCKER'
services:
  postgres:
    image: postgres:16
    container_name: spring-api-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
DOCKER

echo "[4/7] Configurando application.yml..."

mkdir -p "$PROJECT_DIR/src/main/resources"

cat > "$PROJECT_DIR/src/main/resources/application.yml" <<'YAML'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: apppass

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 8080
YAML

echo "[5/7] Inicializando Git..."

cd "$PROJECT_DIR"

git init -b main

git add .

git commit -m "Initial commit generated by DotNetProjectWizard" || true

echo "[6/7] Estrutura criada."

echo "[7/7] Finalizado."

echo
echo "========================================"
echo " Projeto criado com sucesso!"
echo "========================================"
echo
echo "Diretório:"
echo "  $PROJECT_DIR"
echo
echo "Próximos passos:"
echo
echo "cd $PROJECT_DIR"
echo "docker compose up -d"
echo "./mvnw spring-boot:run"
echo
